export { registerAuthRoutes } from './auth';
export { registerUserRoutes } from './users';
export { registerAppointmentRoutes } from './appointments';
export { registerAppointmentPhotoRoutes } from './appointment-photos';
export { registerServiceRoutes } from './services';
export { registerMarketingRoutes } from './marketing';
export { registerNoteTemplateRoutes } from './note-templates';
export { registerNoteHistoryRoutes } from './note-history';
export { registerLocationRoutes } from './locations';
